language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn -DskipTests deploy
  --settings .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn -DskipTests clean install"
  ;fi
env:
  global:
  - secure: JZSgBJ1UXHinEPt7OVN+hgq0W1PjPCfPlD9PLAFhL4EhWZLydfa8i8IThZR/2zlZjJREH70amGaWjwkxA02GvJJMTHY5O2ptePzwcqHr0udADJERQSMaA68klWmM6lGuqE29jdZjLROqlFLpBoI54hcXj/LVR6E4FkAIK5mv2nxOThZkVz0CBkuOoL2bDC0IqHBCBieVK8ZNh0K4BZQFfGp5iCh+2Tbu7eIpJpWE7EzjjuC68KA26qP4x/BLbGnlqDnEjZSo4XbezDnl8G3L8e5KeCtoX8FQmMKcc97a0T0ga9ZTmBWo96egFjeCyIow9hnzGyKrfylzwiq0uiNoLgSwVTnNI8zwdHhEmhQ7l1IuwrBacHUUpDm4ZCFCbY6QZnYHFcC2YKqOMPsQ0J3EdEdrIczI0XFHlFl2I5I/JC3GcMUmbBmSm1QQOzb8PZvOdi5979H0GqygC9HVFcElZgD1qIDdocyKS3uKnNsTpUk045eNSwh1w4TCkN3wWsuDrN3Nyo+wyR0hei3SKlFQWn9nA3aoSSlaMk+FvDPa40aP2OCRamvUsfTlrpRbbg3Kgcex6sFdIEiEqljAdkv1KEFZwswpqQvWfdat2acFaEiCg1pFiOiZBKFV71DjqVbcyCkZaSvh4hYU6VktexX32KskQBHthCxbiY+2ztaMOnc=
  - secure: blEyPOTj8iX1uuYxmgkRwzlK1959jG0PMF17AN7P4K934+Z+tH/L5kouuua4G3N+Hswj5k7L0CVhqSNeV75cIYGfedLSZmLsHn1SNJ8W5vTvDSBq4h2S6h9joxI6OF7fioKWJfsOpOEtJ1rSqjjOFIyR99KEabriWe7yr8+LNqG6QJ7/UkMytRoQGAMnhaOlCClQ2X/Ew1t7+bh7teDdYAbhF3g5XopOoys0N8OL3R93xFO5RxOEN2/voktICOG2wKTLbX3gMMEx6o9X9YVquOuJj2TDwqXZQNOKILcPTl+WhNlZP0MryW3ai15icROsPNeMQi8Nya9PdsAh+Fn6WdKugtOy1JfC5pI2FXPgBUwVneSM9Q97xpjNirlMAHYwTL5ykUaDJYDjGPpyZYMuJBzL8PZUIDvByrqQ9USFUzoOLksub/y9Emx3H0CweT8rf07hEVzQFUBCgdH8S0p1+nhRU7JEjpH4348LyYC3ueHJEQ5rOmYlPPnVhjT4Hni+P2xAc4AAAjLvGIUQGLwhgoq9Ggio8FgJ11fmzzUoJgcmQoRDBHxJEujITESa7h0YDgsPUAaKnusQky/LXrRJp+UQEFHOtoT7I0t+kFlNe/p1K5vePbUURZVE2lsQWHew1PXDTSWvRwuUykBsM/zUQrOnvGRML0k7hiJOb2qxczI=
