version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.x
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "m4SFEW+ZoD016EFGmMsnFY+EuZFylgx+EJKoQgsFQcUKxbW4cTrVTfMnbRS1OF6QvX40WB0xwzbMGCp1z8+xvejAJR2ivzm1gNKs9L2KZn+aNvIfw45n7k7damDT58A7PLRycm0hhuD+8zk8eGb46NEVO3EuGn6aFwMj0sWSKMxaNxHL+yuvFvdxW8P9yba6GCD1QPTLccF6KjmUc5FW0fUlsLvirs99AyQjVg5szWWA4tD+YfKEWShDzEB/wqeIGtL/UNrJPpG0B7ooLWZQDKR517IrqVRyzNHBn8diVyDdm0HFRPNRN8ErTFQQ+UMMpGq9SVUICiuq+SgzzLceTPLxBVsS+ymeEA5/uoUoN6Ccj8t8aP8Iz3V0ZMNGDejsHvOhmtLTGD/y0OW86mYzjxR2s9xcChWDB/o+IkGRF8aUwlLgHrcouKG/0ADm43qTonw3bPlPSVfhczefRy5bNdIC4qdogIws3vkp5n5i3wTN3/YYQs3aSvbCEiuJE1/UWfeuxv5TPZp4Fi6FJxFj1vhgtxF5/CB8k49tFfDvoxi4xOg4GkjiYD4g0msCujUxfXj+qNqTWvdAgzeDz+V6nk7FawWvxuvdvIibl6+YXKmErPKEQLDJMEecyY63PSiLS5EI3v3MKFi38tFaqyYZVCGBQHudOL6Th9Ou9p9UMZA="
        - secure: "ZucI9jH657GcMR4uVb0CaiAgeZI+DVLolbXBBswynI3ek8cctVL2iY6bY3MVujHaqh8LyorssESzrp/BlAvGYr5aBHQMY16q3q4SMjnIKPfYBhZQ9ok/B6/2k/wp3tiCCmY212ZAVRPjWPUhIKNne90tPozFv4ZyVB036d+ppUYDQaiM1h2jUbpZObOsydBqp3PaD2kFuZ9FgkmmibnxTM+fYoHGLFZVNyBbiu6eKZgWJSKmWnl2icriT916yYs5fGUw3NU5yy7ZwIMlX5Q/djTPJfAZN7dzYGlYRRYSTdg4si964kD27wpYV/jrGyHAF4/8by9bg+j1Zt3SMuFw1p0m/jeQfRsih52u6MOBTIQ+jS3ZaLB2tBQMXGfKcSsKxBJoiushvnpAEZo/yQc5XJ3J7UvoTsH/bOGx6svju478mlKJeNXDqlnvxcGZRs6iwBcxFqXKn8mlhbX5JG1oNW8OHkW5+6yBhkrQrf+QgEBrO+Xg23W3qMo/MorMd9eLKzA68fDmAUMSHQCr8fgBEcLg9t2lQU2ZfXHovcGKc1b/HybaG01HSf7UnEXa7R53ALG+z5vCIMVCXwSbl/Z8gYtQs15Wn4g33cUeV1LyClP1yBeZ9TmaoBN1trD3noq2HB1PaZCZr0QS9eIbV7liLfKlvK1oTaAX+12IitUERGI="
